### PR TITLE
fix card component lint errors

### LINKED ISSUE #16171: Fix card component lint errors
Card component causes lint errors during build-test-lint action. 

* HostBinding or HostListener rather than the `host` metadata
* Directive class names should end with one of these suffixes: "Directive"

### PR DESCRIPTION
**Pull request by bariscanyilmaz**
### Description

Resolves #16171 

TODO: add `Directive` suffix to directive components and use `HostBinding` instead of Host
### Checklist

- [x] I fully tested it as developer / designer and created unit / integration tests
- [x] I documented it (or no need to document or I will create a separate documentation issue)

### How to test it?

Please describe how this can be tested by the test engineers if it is not already explicit - or remove this section if no need to description.

### CODE REVIEW

File: npm/ng-packs/packages/theme-shared/src/lib/components/card/card-body.component.ts [hunk 1]
```diff
@@ -1,16 +1,13 @@
...
-    </div>`,
-  host: {
-    class: 'card-body',
-  }
+  template: ` <div [ngClass]="cardBodyClass" [ngStyle]="cardBodyStyle">
+    <ng-content></ng-content>
+  </div>`,
 })
 export class CardBodyComponent {
+  @HostBinding('class') class = 'card-body';
```
Comment (rqx110) [inline npm/ng-packs/packages/theme-shared/src/lib/components/card/card-body.component.ts]: the variable `class` is the keyword of typescript, it is better to rename to other name?

**Review by rqx110 — APPROVED** [review]

**Review by masum-ulu — APPROVED** [review]
