### PR TITLE
Angular - Account Pages Sidebar Flicker on Reload

### LINKED ISSUE #19038: [Angular] Login Page SideBar flicker on reload
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are on the login page and refresh the site, the sidebar flicker and shown for very short amount. Please check the video

### Reproduction Steps

1. Create a multi layered angular app using the cli
2. Run the migration
3. Run the apis
4. Run the angular app
5. Go to login page
6. Refresh the login page

### Expected behavior

It shouldn't flicker and the sidebar shoudn't visible

### Actual behavior

The sidebar is visible for very short amount of time

### Version

8.0.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### PR DESCRIPTION
**Pull request by sumeyyeKurtulus**
### Description

Resolves #19038 and relates #17061.
As another issue was fixed by #17061, the code piece added inside the `ngOnInit` lifecycle hook breaks the account pages and results in a flicker on reload. That is why, we have commented out the related part to propose a solution.

[SidebarFlickerResolved.webm](https://github.com/abpframework/abp/assets/92928815/59d95d8f-5c43-46b9-9b7d-683e78883c05)

### Checklist

- [X] I fully tested it as developer

### How to test it?

You can test it by following the instructions as declared in the issue.

### CODE REVIEW

File: npm/ng-packs/apps/dev-app/src/app/home/home.component.ts [hunk 1]
```diff
@@ -1,17 +1,18 @@
 import { AuthService } from '@abp/ng.core';
-import { Component } from '@angular/core';
+import { Component, inject } from '@angular/core';
 
 @Component({
   selector: 'app-home',
   templateUrl: './home.component.html',
 })
 export class HomeComponent {
+  private authService = inject(AuthService);
```
Comment (masum-ulu) [inline npm/ng-packs/apps/dev-app/src/app/home/home.component.ts]: mark as `protected readonly`

File: npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts [hunk 2]
```diff
@@ -1,49 +1,37 @@
...
   private readonly route = inject(ActivatedRoute);
   private readonly routes = inject(RoutesService);
-  private localizationService = inject(LocalizationService)
-  private replaceableComponents = inject(ReplaceableComponentsService)
-  private subscription = inject(SubscriptionService)
-  private routerEvents = inject(RouterEvents)
+  private localizationService = inject(LocalizationService);
+  private replaceableComponents = inject(ReplaceableComponentsService);
+  private subscription = inject(SubscriptionService);
+  private routerEvents = inject(RouterEvents);
```
Comment (masum-ulu) [inline npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts]: Make them private to `protected readonly`

File: npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts [hunk 3]
```diff
@@ -56,19 +44,17 @@ export class DynamicLayoutComponent implements OnInit {
     if (this.layout) {
       return;
     }
-    this.getLayout()
+    // this.getLayout();
```
Comment (masum-ulu) [inline npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts]: Remove NgOninit

File: npm/ng-packs/packages/theme-basic/src/lib/components/application-layout/application-layout.component.ts [hunk 4]
```diff
@@ -1,21 +1,19 @@
...
 
-
 @Component({
   selector: 'abp-layout-application',
   templateUrl: './application-layout.component.html',
   animations: [slideFromBottom, collapseWithMargin],
   providers: [LayoutService, SubscriptionService],
 })
 export class ApplicationLayoutComponent implements AfterViewInit {
+  public service = inject(LayoutService);
```
Comment (masum-ulu) [inline npm/ng-packs/packages/theme-basic/src/lib/components/application-layout/application-layout.component.ts]: Mark as `public readonly`

**Review by masum-ulu — APPROVED** [review]

**Review by oykuermann — CHANGES_REQUESTED** [review]
After implementing AuthGuard and login, a blank page opened:
image
image

**Comment by sumeyyeKurtulus** [comment]
Hello again @oykuermann I have added a new condition to render the layout and manage the issue mentioned above #17061
fyi @masumulu28

**Review by masum-ulu — APPROVED** [review]

**Review by oykuermann — APPROVED** [review]
