### PR TITLE
Fix getModifierState error at CapsLockDirective

### LINKED ISSUE #17919: Caps lock directive throw an error when you make autocomplete at the specified input
image

### PR DESCRIPTION
**Pull request by Sinan997**
resolves #17919

### CODE REVIEW

File: npm/ng-packs/packages/core/src/lib/directives/caps-lock.directive.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ export class TrackCapsLockDirective {
     if (
       (s.toUpperCase() === s && s.toLowerCase() !== s && e.shiftKey) ||
       (s.toUpperCase() !== s && s.toLowerCase() === s && e.shiftKey) ||
-      e.getModifierState('CapsLock')
+      (e.getModifierState && e.getModifierState('CapsLock'))
```
Comment (masum-ulu) [inline npm/ng-packs/packages/core/src/lib/directives/caps-lock.directive.ts:24]: Can you try `!!e?.getModifierState('CapsLock')` condition ? It this works fine ?

**Review by masum-ulu — APPROVED** [review]

**Review by masum-ulu — APPROVED** [review]
