### PR TITLE
Disabled transaction for sqlite.

### LINKED ISSUE #13738: sqlite databse is locked
The SQLite database is used and the entityframeworkcore is used to generate the application. Click the login button after running the application .The database  is locked exception occurs.
mmexport1660821207716

### PR DESCRIPTION
**Pull request by maliming**
Resolve #13738

### CODE REVIEW

File: templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameEntityFrameworkCoreModule.cs [hunk 1]
```diff
@@ -53,5 +54,12 @@ public override void ConfigureServices(ServiceConfigurationContext context)
                  * See also MyProjectNameMigrationsDbContextFactory for EF Core tooling. */
             options.UseSqlServer();
         });
+
+        //<TEMPLATE-REMOVE IF-NOT='dbms:sqlite'>
```
Comment (rqx110) [inline templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameEntityFrameworkCoreModule.cs]:
```suggestion
        //<TEMPLATE-REMOVE IF-NOT='dbms:SQLite'>
```

**Review by realLiangshiwei — APPROVED** [review]
